---
title: "AquaticsFramework_ConservationGoals"
output: html_document
date: "2023-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

#### Load Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stringr)

```

#### Load Data + Summarize
```{r}
# load csv file
df <- read.csv("transformed_data.csv", header = TRUE, stringsAsFactors = FALSE)

# Add IRA Column
df <- df %>%
  mutate(IRA = grepl("(IRA)", CP_NAME, ignore.case = TRUE))

# Clean up name column
df <- df %>%
  mutate(CP_NAME_1 = str_extract(CP_NAME, "(?<=\\|)(.*?)(?=\\|)")) %>%
  mutate(LABEL_NAME = str_extract(CP_NAME_1, "^[^(]*"))
# 
#   mutate(LABEL_NAME_CLEAN =ifelse(str_detect(LABEL_NAME, "(IRA)"), str_replace(LABEL_NAME, "(IRA)", ""), LABEL_NAME))
# 
#   # Remove all parentheses from the strings column LABEL_NAME_CLEAN 
#   df$LABEL_NAME_CLEAN <- gsub("\\(|\\)", "", df$LABEL_NAME_CLEAN)


# Shorten long words in the name
replacements <- list(
  "Management"  = "Mgmt",
  "Improvement" = "Imprvmt",
  "Development" = "Dvlpmt",
  "System" = "Systm",
  "Treatment" = "Trtmt"
)

# Function to replace words in a given string
replace_words <- function(text) {
   for (word in names(replacements)) {
    text <- str_replace_all(text, fixed(word), replacements[[word]])
   }
  text
}

# Run the shortening function to the label name column
df <- df %>%
  mutate(SHRT_LABEL_NAME = str_trim(map_chr(LABEL_NAME, replace_words)))
  


# Create New Dataframe summarizing the data (Residue and Till Management were collapsed into one category (no till / reduced till))
cpsums <- df %>%
  group_by(SHRT_LABEL_NAME, UNIT, IRA) %>%
  summarize(sum_value = sum(VALUE, na.rm = TRUE)) 

# Create new dataframe with just acres
cpsums_acres <- cpsums %>%
  filter(UNIT == "Ac") %>%
  select(SHRT_LABEL_NAME, sum_value, UNIT, IRA) %>%
  ungroup() %>%
  mutate(pct = sum_value / sum(cpsums_acres$sum_value)*100)

#Create new dataset with only top 10 values cpsums_acres
cpsums_acres_top10 <- cpsums_acres %>%
  slice_max(sum_value, n=10) %>%
  arrange(desc(sum_value))

#Create a new dataset with a new row of all other CPs in acres
cpsums_acres_top11 <- cpsums_acres_top10 %>%
  add_row(SHRT_LABEL_NAME = "All others",
          sum_value = sum(cpsums_acres$sum_value) - sum(cpsums_acres_top10$sum_value),
          UNIT = "Ac",
          IRA = FALSE,
          pct = (sum(cpsums_acres$sum_value)-sum(cpsums_acres_top10$sum_value)) / sum(cpsums_acres$sum_value) *100)

```


#### Basic Plot
```{r}
basic_plot <- ggplot(cpsums_acres_top10, aes(x = as.factor(SHRT_LABEL_NAME), y = sum_value)) +
  geom_bar(stat = "identity", fill=alpha("blue",0.3)) +
  ylim(-2000,38000) +
  theme_minimal() + 
  theme( 
     axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-2,4), "cm")     # This remove unnecessary margin around plot
  ) +
  coord_polar(start = 0)
    
basic_plot
```



```{r}

copied_plt <- ggplot(cpsums_acres_top11) +
  # Make custom panel grid
  geom_hline(
    aes(yintercept = y), 
    data.frame(y = c(0:3) * 10000),
    color = "lightgrey"
  ) + 
  # Add bars to represent the cumulative track lengths
  # str_wrap(region, 5) wraps the text so each line has at most 5 characters
  # (but it doesn't break long words!)
  geom_col(
    aes(
      x = str_wrap(SHRT_LABEL_NAME, 5),
      y = sum_value,
      fill = IRA
    ),
    position = "dodge2",
    show.legend = TRUE,
    alpha = .9
  ) +
  
# 
#   # Lollipop shaft for mean gain per region
#   geom_segment(
#     aes(
#       x = reorder(str_wrap(LABEL_NAME_CLEAN, 5), sum_CP_NAME),
#       y = 0,
#       xend = reorder(str_wrap(LABEL_NAME_CLEAN, 5), sum_CP_NAME),
#       yend = 10000
#     ),
#     linetype = "dashed",
#     color = "gray12"
#   ) + 
  
  # Make it circular!
  coord_polar()+
  theme_minimal()

copied_plt
```

## Notes on Next Steps
1. Get the sizes right, Remove unnecessary labels 
2. Calculate % of total coverage for each CP (using totals from cpsums_acres) (would be nice if this was a column)
3. ADD to cpsums_acres_top10 a line of data for "All Other CPs" 
https://r-graph-gallery.com/web-circular-barplot-with-R-and-ggplot2.html


####
```{r}
# Set a number of 'empty bar' to add at the end of each group
empty_bar <- 4
to_add <- data.frame( matrix(NA, empty_bar*nlevels(data$group), ncol(data)) )
colnames(to_add) <- colnames(data)
to_add$group <- rep(levels(data$group), each=empty_bar)
data <- rbind(data, to_add)
data <- data %>% arrange(group)
data$id <- seq(1, nrow(data))



```  

